//! Node-type blueprint: defines the kind of a [`Node`](crate::node::Node).
//!
//! A `NodeType` is the runtime representation of a template's declaration
//! "a node of this kind exists, is named X, and carries the following
//! properties". In Python this lives in
//! `backend/infra/schema_loader.py::NodeTypeDef` and carries a lot of
//! legacy debt (legacy-id + uuid duality, `_extra_props` bag, mutable
//! feature flags). This Rust port starts with the irreducible minimum
//! and layers behaviour in subsequent cycles.

use serde::{Deserialize, Serialize};

use crate::ids::NodeTypeId;

/// Schema version for serialized `NodeType`. Bump on any breaking shape
/// change so the migration layer can route old payloads correctly.
pub const NODE_TYPE_SCHEMA_VERSION: u32 = 1;

/// A node-type definition. Identifies a kind of node and gives it a name.
///
/// Future cycles will extend this with `allowed_properties` and
/// `allowed_children` once their behaviour is locked behind tests.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NodeType {
    id: NodeTypeId,
    name: String,
    schema_version: u32,
}

impl NodeType {
    /// Mint a new `NodeType` with a fresh [`NodeTypeId`] and the given name.
    ///
    /// The id is generated by `Uuid::new_v4` per the §4a "one ID
    /// generator" rule. There is no public constructor that accepts an
    /// explicit id outside of test scaffolding.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: NodeTypeId::new(),
            name: name.into(),
            schema_version: NODE_TYPE_SCHEMA_VERSION,
        }
    }

    /// The stable identifier for this node type.
    #[must_use]
    pub fn id(&self) -> NodeTypeId {
        self.id
    }

    /// Human-readable name (display only; not a key).
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// On-disk schema version of this struct.
    #[must_use]
    pub fn schema_version(&self) -> u32 {
        self.schema_version
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_node_type_has_unique_id_and_given_name() {
        let a = NodeType::new("Equipment");
        let b = NodeType::new("Equipment");
        assert_ne!(a.id(), b.id(), "each NodeType gets a fresh id");
        assert_eq!(a.name(), "Equipment");
        assert_eq!(a.schema_version(), NODE_TYPE_SCHEMA_VERSION);
    }

    #[test]
    fn node_type_roundtrips_through_json() {
        let nt = NodeType::new("Person");
        let json = serde_json::to_string(&nt).unwrap();
        let parsed: NodeType = serde_json::from_str(&json).unwrap();
        assert_eq!(nt, parsed);
    }
}
