//! Node-type blueprint: defines the kind of a [`Node`](crate::node::Node).
//!
//! A `NodeType` is the runtime representation of a template's declaration
//! "a node of this kind exists, is named X, and carries the following
//! properties". In Python this lives in
//! `backend/infra/schema_loader.py::NodeTypeDef` and carries a lot of
//! legacy debt (legacy-id + uuid duality, `_extra_props` bag, mutable
//! feature flags). This Rust port starts with the irreducible minimum
//! and layers behaviour in subsequent cycles.

use indexmap::IndexSet;
use serde::{Deserialize, Serialize};

use crate::ids::{NodeTypeId, PropertyId};

/// Schema version for serialized `NodeType`. Bump on any breaking shape
/// change so the migration layer can route old payloads correctly.
pub const NODE_TYPE_SCHEMA_VERSION: u32 = 1;

/// A node-type definition. Identifies a kind of node and gives it a name.
///
/// Future cycles will extend this with `allowed_properties` and
/// `allowed_children` once their behaviour is locked behind tests.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NodeType {
    id: NodeTypeId,
    name: String,
    schema_version: u32,
    #[serde(default)]
    allowed_properties: IndexSet<PropertyId>,
    #[serde(default)]
    allowed_children: IndexSet<NodeTypeId>,
}

impl NodeType {
    /// Mint a new `NodeType` with a fresh [`NodeTypeId`] and the given name.
    ///
    /// The id is generated by `Uuid::new_v4` per the §4a "one ID
    /// generator" rule. There is no public constructor that accepts an
    /// explicit id outside of test scaffolding.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: NodeTypeId::new(),
            name: name.into(),
            schema_version: NODE_TYPE_SCHEMA_VERSION,
            allowed_properties: IndexSet::new(),
            allowed_children: IndexSet::new(),
        }
    }

    /// The stable identifier for this node type.
    #[must_use]
    pub fn id(&self) -> NodeTypeId {
        self.id
    }

    /// Human-readable name (display only; not a key).
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// On-disk schema version of this struct.
    #[must_use]
    pub fn schema_version(&self) -> u32 {
        self.schema_version
    }

    /// Return a new `NodeType` with `pid` added to the allowed-property set.
    ///
    /// Adding the same `pid` twice is a no-op (allowlist is a set, not a
    /// multiset). Insertion order is preserved for callers that iterate
    /// via [`Self::allowed_properties`].
    #[must_use]
    pub fn with_allowed_property(mut self, pid: PropertyId) -> Self {
        self.allowed_properties.insert(pid);
        self
    }

    /// `true` iff `pid` is in the allowed-property allowlist.
    #[must_use]
    pub fn allows_property(&self, pid: PropertyId) -> bool {
        self.allowed_properties.contains(&pid)
    }

    /// Iterate the allowed-property ids in insertion order.
    pub fn allowed_properties(&self) -> impl Iterator<Item = PropertyId> + '_ {
        self.allowed_properties.iter().copied()
    }

    /// Return a new `NodeType` with `child_kind` added to the allowed-child set.
    ///
    /// Same semantics as [`Self::with_allowed_property`]: idempotent on
    /// repeat, insertion order preserved.
    #[must_use]
    pub fn with_allowed_child(mut self, child_kind: NodeTypeId) -> Self {
        self.allowed_children.insert(child_kind);
        self
    }

    /// `true` iff `child_kind` is in the allowed-child allowlist.
    #[must_use]
    pub fn allows_child(&self, child_kind: NodeTypeId) -> bool {
        self.allowed_children.contains(&child_kind)
    }

    /// Iterate the allowed-child ids in insertion order.
    pub fn allowed_children(&self) -> impl Iterator<Item = NodeTypeId> + '_ {
        self.allowed_children.iter().copied()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_node_type_has_unique_id_and_given_name() {
        let a = NodeType::new("Equipment");
        let b = NodeType::new("Equipment");
        assert_ne!(a.id(), b.id(), "each NodeType gets a fresh id");
        assert_eq!(a.name(), "Equipment");
        assert_eq!(a.schema_version(), NODE_TYPE_SCHEMA_VERSION);
    }

    #[test]
    fn node_type_roundtrips_through_json() {
        let nt = NodeType::new("Person");
        let json = serde_json::to_string(&nt).unwrap();
        let parsed: NodeType = serde_json::from_str(&json).unwrap();
        assert_eq!(nt, parsed);
    }

    #[test]
    fn new_node_type_has_no_allowed_properties() {
        let nt = NodeType::new("Equipment");
        let pid = crate::ids::PropertyId::new();
        assert!(!nt.allows_property(pid));
        assert_eq!(nt.allowed_properties().count(), 0);
    }

    #[test]
    fn with_allowed_property_adds_to_allowlist() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment").with_allowed_property(pid);
        assert!(nt.allows_property(pid));
        assert_eq!(nt.allowed_properties().collect::<Vec<_>>(), vec![pid]);
    }

    #[test]
    fn with_allowed_property_is_idempotent() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment")
            .with_allowed_property(pid)
            .with_allowed_property(pid);
        assert_eq!(
            nt.allowed_properties().count(),
            1,
            "the same id added twice still counts once"
        );
    }

    #[test]
    fn allowed_properties_preserve_insertion_order() {
        let pid1 = crate::ids::PropertyId::new();
        let pid2 = crate::ids::PropertyId::new();
        let pid3 = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment")
            .with_allowed_property(pid1)
            .with_allowed_property(pid2)
            .with_allowed_property(pid3);
        assert_eq!(
            nt.allowed_properties().collect::<Vec<_>>(),
            vec![pid1, pid2, pid3]
        );
    }

    #[test]
    fn new_node_type_has_no_allowed_children() {
        let nt = NodeType::new("Project");
        let child_kind = crate::ids::NodeTypeId::new();
        assert!(!nt.allows_child(child_kind));
        assert_eq!(nt.allowed_children().count(), 0);
    }

    #[test]
    fn with_allowed_child_adds_to_allowlist() {
        let child_kind = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project").with_allowed_child(child_kind);
        assert!(nt.allows_child(child_kind));
        assert_eq!(nt.allowed_children().collect::<Vec<_>>(), vec![child_kind]);
    }

    #[test]
    fn with_allowed_child_is_idempotent() {
        let child_kind = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project")
            .with_allowed_child(child_kind)
            .with_allowed_child(child_kind);
        assert_eq!(nt.allowed_children().count(), 1);
    }

    #[test]
    fn allowed_children_preserve_insertion_order() {
        let k1 = crate::ids::NodeTypeId::new();
        let k2 = crate::ids::NodeTypeId::new();
        let k3 = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project")
            .with_allowed_child(k1)
            .with_allowed_child(k2)
            .with_allowed_child(k3);
        assert_eq!(nt.allowed_children().collect::<Vec<_>>(), vec![k1, k2, k3]);
    }
}
