//! Node-type blueprint: defines the kind of a [`Node`](crate::node::Node).
//!
//! A `NodeType` is the runtime representation of a template's declaration
//! "a node of this kind exists, is named X, and carries the following
//! properties". In Python this lives in
//! `backend/infra/schema_loader.py::NodeTypeDef` and carries a lot of
//! legacy debt (legacy-id + uuid duality, `_extra_props` bag, mutable
//! feature flags). This Rust port starts with the irreducible minimum
//! and layers behaviour in subsequent cycles.

use indexmap::{IndexMap, IndexSet};
use serde::{Deserialize, Serialize};

use crate::ids::{NodeTypeId, PropertyId};
use crate::velocity::{NodeVelocityConfig, PropertyVelocityConfig, SelectOption};

/// Schema version for serialized `NodeType`. Bump on any breaking shape
/// change so the migration layer can route old payloads correctly.
pub const NODE_TYPE_SCHEMA_VERSION: u32 = 1;

/// A node-type definition. Identifies a kind of node and gives it a name.
///
/// Future cycles will extend this with `allowed_properties` and
/// `allowed_children` once their behaviour is locked behind tests.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NodeType {
    id: NodeTypeId,
    name: String,
    schema_version: u32,
    #[serde(default)]
    allowed_properties: IndexSet<PropertyId>,
    #[serde(default)]
    allowed_children: IndexSet<NodeTypeId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    velocity_config: Option<NodeVelocityConfig>,
    #[serde(default, skip_serializing_if = "IndexMap::is_empty")]
    property_velocity_configs: IndexMap<PropertyId, PropertyVelocityConfig>,
    #[serde(default, skip_serializing_if = "IndexMap::is_empty")]
    property_select_options: IndexMap<PropertyId, Vec<SelectOption>>,
}

impl NodeType {
    /// Mint a new `NodeType` with a fresh [`NodeTypeId`] and the given name.
    ///
    /// The id is generated by `Uuid::new_v4` per the §4a "one ID
    /// generator" rule. There is no public constructor that accepts an
    /// explicit id outside of test scaffolding.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: NodeTypeId::new(),
            name: name.into(),
            schema_version: NODE_TYPE_SCHEMA_VERSION,
            allowed_properties: IndexSet::new(),
            allowed_children: IndexSet::new(),
            velocity_config: None,
            property_velocity_configs: IndexMap::new(),
            property_select_options: IndexMap::new(),
        }
    }

    /// Build a `NodeType` with a caller-supplied id, for deterministic
    /// snapshot fixtures only.
    #[cfg(test)]
    pub(crate) fn with_id_for_test(id: NodeTypeId, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            schema_version: NODE_TYPE_SCHEMA_VERSION,
            allowed_properties: IndexSet::new(),
            allowed_children: IndexSet::new(),
            velocity_config: None,
            property_velocity_configs: IndexMap::new(),
            property_select_options: IndexMap::new(),
        }
    }

    /// The stable identifier for this node type.
    #[must_use]
    pub fn id(&self) -> NodeTypeId {
        self.id
    }

    /// Human-readable name (display only; not a key).
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// On-disk schema version of this struct.
    #[must_use]
    pub fn schema_version(&self) -> u32 {
        self.schema_version
    }

    /// Return a new `NodeType` with `pid` added to the allowed-property set.
    ///
    /// Adding the same `pid` twice is a no-op (allowlist is a set, not a
    /// multiset). Insertion order is preserved for callers that iterate
    /// via [`Self::allowed_properties`].
    #[must_use]
    pub fn with_allowed_property(mut self, pid: PropertyId) -> Self {
        self.allowed_properties.insert(pid);
        self
    }

    /// `true` iff `pid` is in the allowed-property allowlist.
    #[must_use]
    pub fn allows_property(&self, pid: PropertyId) -> bool {
        self.allowed_properties.contains(&pid)
    }

    /// Iterate the allowed-property ids in insertion order.
    pub fn allowed_properties(&self) -> impl Iterator<Item = PropertyId> + '_ {
        self.allowed_properties.iter().copied()
    }

    /// Return a new `NodeType` with `child_kind` added to the allowed-child set.
    ///
    /// Same semantics as [`Self::with_allowed_property`]: idempotent on
    /// repeat, insertion order preserved.
    #[must_use]
    pub fn with_allowed_child(mut self, child_kind: NodeTypeId) -> Self {
        self.allowed_children.insert(child_kind);
        self
    }

    /// `true` iff `child_kind` is in the allowed-child allowlist.
    #[must_use]
    pub fn allows_child(&self, child_kind: NodeTypeId) -> bool {
        self.allowed_children.contains(&child_kind)
    }

    /// Iterate the allowed-child ids in insertion order.
    pub fn allowed_children(&self) -> impl Iterator<Item = NodeTypeId> + '_ {
        self.allowed_children.iter().copied()
    }

    /// Return a new `NodeType` carrying a node-level velocity config.
    #[must_use]
    pub fn with_velocity_config(mut self, config: NodeVelocityConfig) -> Self {
        self.velocity_config = Some(config);
        self
    }

    /// Return a new `NodeType` with a per-property velocity config attached.
    ///
    /// Re-attaching the same `pid` overwrites the previous config.
    #[must_use]
    pub fn with_property_velocity_config(
        mut self,
        pid: PropertyId,
        config: PropertyVelocityConfig,
    ) -> Self {
        self.property_velocity_configs.insert(pid, config);
        self
    }

    /// The node-level velocity config, if any.
    ///
    /// Mirrors Python `_get_node_level_velocity_config`.
    #[must_use]
    pub fn velocity_config(&self) -> Option<&NodeVelocityConfig> {
        self.velocity_config.as_ref()
    }

    /// The velocity config attached to `pid`, if any.
    #[must_use]
    pub fn property_velocity_config(&self, pid: PropertyId) -> Option<&PropertyVelocityConfig> {
        self.property_velocity_configs.get(&pid)
    }

    /// Iterate the per-property velocity configs in insertion order.
    ///
    /// Mirrors the Python engine walking a node type's property definitions
    /// to find their `velocityConfig` blocks.
    pub fn property_velocity_configs(
        &self,
    ) -> impl Iterator<Item = (PropertyId, &PropertyVelocityConfig)> + '_ {
        self.property_velocity_configs
            .iter()
            .map(|(pid, cfg)| (*pid, cfg))
    }

    /// Return a new `NodeType` with `pid`'s select-option list attached.
    ///
    /// These mirror a select property's `options` array in the Python
    /// schema and let the velocity status mode resolve a stored option id
    /// to the option name that `statusScores` is keyed by. Re-attaching the
    /// same `pid` overwrites the previous list.
    #[must_use]
    pub fn with_property_select_options(
        mut self,
        pid: PropertyId,
        options: Vec<SelectOption>,
    ) -> Self {
        self.property_select_options.insert(pid, options);
        self
    }

    /// The select-option list attached to `pid`, or an empty slice when the
    /// property has none.
    #[must_use]
    pub fn property_select_options(&self, _pid: PropertyId) -> &[SelectOption] {
        &[]
    }

    /// `true` iff this node type carries any velocity configuration —
    /// either a node-level config or at least one *enabled* per-property
    /// config. Mirrors Python `_has_velocity_config`.
    #[must_use]
    pub fn has_velocity_config(&self) -> bool {
        self.velocity_config.is_some() || self.property_velocity_configs.values().any(|c| c.enabled)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_node_type_has_unique_id_and_given_name() {
        let a = NodeType::new("Equipment");
        let b = NodeType::new("Equipment");
        assert_ne!(a.id(), b.id(), "each NodeType gets a fresh id");
        assert_eq!(a.name(), "Equipment");
        assert_eq!(a.schema_version(), NODE_TYPE_SCHEMA_VERSION);
    }

    #[test]
    fn node_type_roundtrips_through_json() {
        let nt = NodeType::new("Person");
        let json = serde_json::to_string(&nt).unwrap();
        let parsed: NodeType = serde_json::from_str(&json).unwrap();
        assert_eq!(nt, parsed);
    }

    #[test]
    fn new_node_type_has_no_allowed_properties() {
        let nt = NodeType::new("Equipment");
        let pid = crate::ids::PropertyId::new();
        assert!(!nt.allows_property(pid));
        assert_eq!(nt.allowed_properties().count(), 0);
    }

    #[test]
    fn with_allowed_property_adds_to_allowlist() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment").with_allowed_property(pid);
        assert!(nt.allows_property(pid));
        assert_eq!(nt.allowed_properties().collect::<Vec<_>>(), vec![pid]);
    }

    #[test]
    fn with_allowed_property_is_idempotent() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment")
            .with_allowed_property(pid)
            .with_allowed_property(pid);
        assert_eq!(
            nt.allowed_properties().count(),
            1,
            "the same id added twice still counts once"
        );
    }

    #[test]
    fn allowed_properties_preserve_insertion_order() {
        let pid1 = crate::ids::PropertyId::new();
        let pid2 = crate::ids::PropertyId::new();
        let pid3 = crate::ids::PropertyId::new();
        let nt = NodeType::new("Equipment")
            .with_allowed_property(pid1)
            .with_allowed_property(pid2)
            .with_allowed_property(pid3);
        assert_eq!(
            nt.allowed_properties().collect::<Vec<_>>(),
            vec![pid1, pid2, pid3]
        );
    }

    #[test]
    fn new_node_type_has_no_allowed_children() {
        let nt = NodeType::new("Project");
        let child_kind = crate::ids::NodeTypeId::new();
        assert!(!nt.allows_child(child_kind));
        assert_eq!(nt.allowed_children().count(), 0);
    }

    #[test]
    fn with_allowed_child_adds_to_allowlist() {
        let child_kind = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project").with_allowed_child(child_kind);
        assert!(nt.allows_child(child_kind));
        assert_eq!(nt.allowed_children().collect::<Vec<_>>(), vec![child_kind]);
    }

    #[test]
    fn with_allowed_child_is_idempotent() {
        let child_kind = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project")
            .with_allowed_child(child_kind)
            .with_allowed_child(child_kind);
        assert_eq!(nt.allowed_children().count(), 1);
    }

    #[test]
    fn allowed_children_preserve_insertion_order() {
        let k1 = crate::ids::NodeTypeId::new();
        let k2 = crate::ids::NodeTypeId::new();
        let k3 = crate::ids::NodeTypeId::new();
        let nt = NodeType::new("Project")
            .with_allowed_child(k1)
            .with_allowed_child(k2)
            .with_allowed_child(k3);
        assert_eq!(nt.allowed_children().collect::<Vec<_>>(), vec![k1, k2, k3]);
    }

    use std::collections::HashMap;

    use crate::velocity::{
        NodeVelocityConfig, PropertyVelocityConfig, PropertyVelocityMode, ScoreMode,
    };

    fn checkbox_config(enabled: bool) -> PropertyVelocityConfig {
        PropertyVelocityConfig {
            enabled,
            mode: PropertyVelocityMode::Checkbox {
                checked_score: 1.0,
                unchecked_score: 0.0,
            },
        }
    }

    #[test]
    fn new_node_type_has_no_velocity_config() {
        let nt = NodeType::new("Task");
        assert!(nt.velocity_config().is_none());
        assert!(!nt.has_velocity_config());
    }

    #[test]
    fn with_velocity_config_stores_node_level() {
        let cfg = NodeVelocityConfig {
            base_score: 5.0,
            score_mode: ScoreMode::Inherit,
        };
        let nt = NodeType::new("Task").with_velocity_config(cfg.clone());
        assert_eq!(nt.velocity_config(), Some(&cfg));
    }

    #[test]
    fn has_velocity_config_true_for_node_level() {
        let cfg = NodeVelocityConfig {
            base_score: 1.0,
            score_mode: ScoreMode::Fixed,
        };
        let nt = NodeType::new("Task").with_velocity_config(cfg);
        assert!(nt.has_velocity_config());
    }

    #[test]
    fn has_velocity_config_true_for_enabled_property() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task").with_property_velocity_config(pid, checkbox_config(true));
        assert!(nt.has_velocity_config());
    }

    #[test]
    fn has_velocity_config_false_for_disabled_property() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task").with_property_velocity_config(pid, checkbox_config(false));
        assert!(!nt.has_velocity_config());
    }

    #[test]
    fn with_property_velocity_config_stores() {
        let pid = crate::ids::PropertyId::new();
        let cfg = PropertyVelocityConfig {
            enabled: true,
            mode: PropertyVelocityMode::Multiplier {
                multiplier_factor: 2.0,
                penalty_mode: false,
            },
        };
        let nt = NodeType::new("Task").with_property_velocity_config(pid, cfg.clone());
        assert_eq!(nt.property_velocity_config(pid), Some(&cfg));
    }

    #[test]
    fn velocity_config_roundtrips_through_json() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task")
            .with_velocity_config(NodeVelocityConfig {
                base_score: 3.0,
                score_mode: ScoreMode::Inherit,
            })
            .with_property_velocity_config(
                pid,
                PropertyVelocityConfig {
                    enabled: true,
                    mode: PropertyVelocityMode::Status {
                        status_scores: HashMap::new(),
                    },
                },
            );
        let json = serde_json::to_string(&nt).unwrap();
        let parsed: NodeType = serde_json::from_str(&json).unwrap();
        assert_eq!(nt, parsed);
    }

    fn opt(id: &str, name: &str) -> SelectOption {
        SelectOption {
            id: id.to_string(),
            name: name.to_string(),
        }
    }

    #[test]
    fn new_node_type_has_no_select_options() {
        let nt = NodeType::new("Task");
        let pid = crate::ids::PropertyId::new();
        assert!(nt.property_select_options(pid).is_empty());
    }

    #[test]
    fn with_property_select_options_stores_list() {
        let pid = crate::ids::PropertyId::new();
        let options = vec![opt("id_a", "Alpha"), opt("id_b", "Beta")];
        let nt = NodeType::new("Task").with_property_select_options(pid, options.clone());
        assert_eq!(nt.property_select_options(pid), options.as_slice());
    }

    #[test]
    fn property_select_options_empty_for_unknown_pid() {
        let pid = crate::ids::PropertyId::new();
        let other = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task").with_property_select_options(pid, vec![opt("x", "X")]);
        assert!(nt.property_select_options(other).is_empty());
    }

    #[test]
    fn with_property_select_options_overwrites_same_pid() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task")
            .with_property_select_options(pid, vec![opt("old", "Old")])
            .with_property_select_options(pid, vec![opt("new", "New")]);
        assert_eq!(
            nt.property_select_options(pid),
            [opt("new", "New")].as_slice()
        );
    }

    #[test]
    fn select_options_roundtrip_through_json() {
        let pid = crate::ids::PropertyId::new();
        let nt = NodeType::new("Task")
            .with_property_select_options(pid, vec![opt("id_a", "Alpha"), opt("id_b", "Beta")]);
        let json = serde_json::to_string(&nt).unwrap();
        let parsed: NodeType = serde_json::from_str(&json).unwrap();
        assert_eq!(nt, parsed);
    }
}
